ASFLAGS_ADDITIONAL = -march=armv7-a -mfloat-abi=hard -mfpu=neon
BusyBox_Linux_ARM_Cortex_A_QEMU = C:/PROGRA~3/MATLAB/SUPPOR~1/R2017b/ARMCOR~1
TARGET_LOAD_CMD = 
TARGET_LOAD_CMD_ARGS = 
TARGET_PKG_INSTALLDIR = C:/PROGRA~3/MATLAB/SUPPOR~1/R2017b/toolbox/target/SUPPOR~1/ARM_CO~1/registry/..
STACK_SIZE = 64
